export const commonMajors = [
  "Accounting",
  "Aerospace Engineering",
  "Agriculture",
  "Anthropology",
  "Architecture",
  "Art History",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communications",
  "Computer Engineering",
  "Computer Science",
  "Criminal Justice",
  "Data Science",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Elementary Education",
  "English",
  "Environmental Science",
  "Film Studies",
  "Finance",
  "Graphic Design",
  "Health Sciences",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Information Technology",
  "International Business",
  "International Relations",
  "Journalism",
  "Kinesiology",
  "Law",
  "Liberal Arts",
  "Management",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Music",
  "Nursing",
  "Nutrition",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Public Relations",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Statistics",
  "Theater",
  "Veterinary Science"
];

export const searchMajors = (searchTerm: string): string[] => {
  const lowercaseSearch = searchTerm.toLowerCase();
  return commonMajors
    .filter(major => major.toLowerCase().includes(lowercaseSearch))
    .slice(0, 10); // Return max 10 suggestions
};